---
title: "Tommy John Surgery Histogram"
author: "Riley Feltner"
date: "2022-11-22"
output: html_document
---

```{r}
TJ <- read.csv("Tommy John Surgery List (@MLBPlayerAnalys) - TJ List.csv")
```

#clean the data
```{r}
library(dplyr)

#MLB, MiLB, NCAA
Cleaned <- subset(TJ, TJ$Month !=1 | TJ$Day != 1) #A lot of Surgery dates were on 1/1 which is unlikely so they were deleted.
Cleaned <- subset(Cleaned, Cleaned$Year >= 2010) #2010-Present

#NCAA
NCAA <- subset(Cleaned, Level == "Coll")

#MLB, MiLB
CleanedNoColl <- subset(Cleaned, Cleaned$Level != "Coll") #Remove College Pitchers
```

#histogram
```{r}
#MLB MiLB NCAA
library(ggplot2)
ggplot(data = Cleaned, mapping = aes(x = Month, y = ))+
  geom_bar(color = "brown3", fill = "dodgerblue4")+
  theme_classic()+
  xlab(1:12)+
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12))+
  labs(title = "MLB, MiLB, NCAA Tommy John Surgeries by Month",
       subtitle = "2010-Present",
       y = "Number of Surgeries",
       x = "Month", 
       caption = "Data: MLBPlayerAnalys | Riley Feltner")


#MLB MiLB
ggplot(data = CleanedNoColl, mapping = aes(x = Month, y = ))+
  geom_bar(color = "brown3", fill = "dodgerblue4")+
  theme_classic()+
  xlab(1:12)+
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12))+
  labs(title = "MLB, MiLB Tommy John Surgeries by Month",
       subtitle = "2010-Present",
       y = "Number of Surgeries",
       x = "Month", 
       caption = "Data: MLBPlayerAnalys | Riley Feltner")


#NCAA
ggplot(data = NCAA, mapping = aes(x = Month, y = ))+
  geom_bar(color = "brown3", fill = "dodgerblue4")+
  theme_classic()+
  xlab(1:12)+
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12))+
  labs(title = "NCAA Tommy John Surgeries by Month",
       subtitle = "2010-Present",
       y = "Number of Surgeries",
       x = "Month", 
       caption = "Data: MLBPlayerAnalys | Riley Feltner")
```

